/**
 * TCG concept data — checklists, authored raw near-mint values, and print
 * runs for the two collectible sets. Generated from presets/pokemon-concept
 * .json; values are honest market ballparks (Base Set priced as 1st
 * Edition vintage, 151 priced as modern retail with its ex/secret chase).
 * Pure data: the engine builds populations and packs from this.
 */

export interface TcgCardData {
  num: number;
  name: string;
  type: string;
  rarity: 'common' | 'uncommon' | 'rare' | 'holo' | 'chase';
  kind: 'creature' | 'trainer' | 'energy' | 'artifact';
  /** Raw near-mint market value, USD. */
  value: number;
  hp: number | null;
  printRun: number;
  /** Display denominator when it differs from the set size (secret rares). */
  outOf?: number;
}

export interface TcgSetData {
  id: string;
  name: string;
  year: number;
  size: number;
  /** Booster structure. */
  packPrice: number;
  boxPrice: number;
  cards: TcgCardData[];
}

export const TCG_SETS: TcgSetData[] = [
  {
    id: 'tcg-base', name: '1999 Base Set — 1st Edition', year: 1999, size: 102,
    packPrice: 3500, boxPrice: 110000,
    cards: [
  { num: 1, name: 'Alakazam', type: 'psychic', rarity: 'holo', kind: 'creature', hp: 80, value: 900, printRun: 3000 },
  { num: 2, name: 'Blastoise', type: 'water', rarity: 'holo', kind: 'creature', hp: 100, value: 2800, printRun: 3000 },
  { num: 3, name: 'Chansey', type: 'colorless', rarity: 'holo', kind: 'creature', hp: 120, value: 1000, printRun: 3000 },
  { num: 4, name: 'Charizard', type: 'fire', rarity: 'holo', kind: 'creature', hp: 120, value: 22000, printRun: 3000 },
  { num: 5, name: 'Clefairy', type: 'colorless', rarity: 'holo', kind: 'creature', hp: 40, value: 600, printRun: 3000 },
  { num: 6, name: 'Gyarados', type: 'water', rarity: 'holo', kind: 'creature', hp: 100, value: 800, printRun: 3000 },
  { num: 7, name: 'Hitmonchan', type: 'fighting', rarity: 'holo', kind: 'creature', hp: 70, value: 500, printRun: 3000 },
  { num: 8, name: 'Machamp', type: 'fighting', rarity: 'holo', kind: 'creature', hp: 100, value: 300, printRun: 3000 },
  { num: 9, name: 'Magneton', type: 'lightning', rarity: 'holo', kind: 'creature', hp: 60, value: 450, printRun: 3000 },
  { num: 10, name: 'Mewtwo', type: 'psychic', rarity: 'holo', kind: 'creature', hp: 60, value: 900, printRun: 3000 },
  { num: 11, name: 'Nidoking', type: 'grass', rarity: 'holo', kind: 'creature', hp: 90, value: 550, printRun: 3000 },
  { num: 12, name: 'Ninetales', type: 'fire', rarity: 'holo', kind: 'creature', hp: 80, value: 700, printRun: 3000 },
  { num: 13, name: 'Poliwrath', type: 'water', rarity: 'holo', kind: 'creature', hp: 90, value: 450, printRun: 3000 },
  { num: 14, name: 'Raichu', type: 'lightning', rarity: 'holo', kind: 'creature', hp: 80, value: 1000, printRun: 3000 },
  { num: 15, name: 'Venusaur', type: 'grass', rarity: 'holo', kind: 'creature', hp: 100, value: 2400, printRun: 3000 },
  { num: 16, name: 'Zapdos', type: 'lightning', rarity: 'holo', kind: 'creature', hp: 90, value: 800, printRun: 3000 },
  { num: 17, name: 'Beedrill', type: 'grass', rarity: 'rare', kind: 'creature', hp: 80, value: 90, printRun: 5000 },
  { num: 18, name: 'Dragonair', type: 'colorless', rarity: 'rare', kind: 'creature', hp: 80, value: 140, printRun: 5000 },
  { num: 19, name: 'Dugtrio', type: 'fighting', rarity: 'rare', kind: 'creature', hp: 70, value: 70, printRun: 5000 },
  { num: 20, name: 'Electabuzz', type: 'lightning', rarity: 'rare', kind: 'creature', hp: 70, value: 80, printRun: 5000 },
  { num: 21, name: 'Electrode', type: 'lightning', rarity: 'rare', kind: 'creature', hp: 80, value: 60, printRun: 5000 },
  { num: 22, name: 'Pidgeotto', type: 'colorless', rarity: 'rare', kind: 'creature', hp: 60, value: 70, printRun: 5000 },
  { num: 23, name: 'Arcanine', type: 'fire', rarity: 'uncommon', kind: 'creature', hp: 100, value: 45, printRun: 15000 },
  { num: 24, name: 'Charmeleon', type: 'fire', rarity: 'uncommon', kind: 'creature', hp: 80, value: 60, printRun: 15000 },
  { num: 25, name: 'Dewgong', type: 'water', rarity: 'uncommon', kind: 'creature', hp: 80, value: 25, printRun: 15000 },
  { num: 26, name: 'Dratini', type: 'colorless', rarity: 'uncommon', kind: 'creature', hp: 40, value: 35, printRun: 15000 },
  { num: 27, name: 'Farfetch\'d', type: 'colorless', rarity: 'uncommon', kind: 'creature', hp: 50, value: 22, printRun: 15000 },
  { num: 28, name: 'Growlithe', type: 'fire', rarity: 'uncommon', kind: 'creature', hp: 60, value: 30, printRun: 15000 },
  { num: 29, name: 'Haunter', type: 'psychic', rarity: 'uncommon', kind: 'creature', hp: 60, value: 30, printRun: 15000 },
  { num: 30, name: 'Ivysaur', type: 'grass', rarity: 'uncommon', kind: 'creature', hp: 60, value: 40, printRun: 15000 },
  { num: 31, name: 'Jynx', type: 'psychic', rarity: 'uncommon', kind: 'creature', hp: 70, value: 22, printRun: 15000 },
  { num: 32, name: 'Kadabra', type: 'psychic', rarity: 'uncommon', kind: 'creature', hp: 60, value: 35, printRun: 15000 },
  { num: 33, name: 'Kakuna', type: 'grass', rarity: 'uncommon', kind: 'creature', hp: 80, value: 20, printRun: 15000 },
  { num: 34, name: 'Machoke', type: 'fighting', rarity: 'uncommon', kind: 'creature', hp: 80, value: 22, printRun: 15000 },
  { num: 35, name: 'Magikarp', type: 'water', rarity: 'uncommon', kind: 'creature', hp: 30, value: 40, printRun: 15000 },
  { num: 36, name: 'Magmar', type: 'fire', rarity: 'uncommon', kind: 'creature', hp: 50, value: 25, printRun: 15000 },
  { num: 37, name: 'Nidorino', type: 'grass', rarity: 'uncommon', kind: 'creature', hp: 60, value: 22, printRun: 15000 },
  { num: 38, name: 'Poliwhirl', type: 'water', rarity: 'uncommon', kind: 'creature', hp: 60, value: 22, printRun: 15000 },
  { num: 39, name: 'Porygon', type: 'colorless', rarity: 'uncommon', kind: 'creature', hp: 30, value: 28, printRun: 15000 },
  { num: 40, name: 'Raticate', type: 'colorless', rarity: 'uncommon', kind: 'creature', hp: 60, value: 22, printRun: 15000 },
  { num: 41, name: 'Seel', type: 'water', rarity: 'uncommon', kind: 'creature', hp: 60, value: 20, printRun: 15000 },
  { num: 42, name: 'Wartortle', type: 'water', rarity: 'uncommon', kind: 'creature', hp: 70, value: 45, printRun: 15000 },
  { num: 43, name: 'Abra', type: 'psychic', rarity: 'common', kind: 'creature', hp: 30, value: 14, printRun: 22000 },
  { num: 44, name: 'Bulbasaur', type: 'grass', rarity: 'common', kind: 'creature', hp: 40, value: 30, printRun: 22000 },
  { num: 45, name: 'Caterpie', type: 'grass', rarity: 'common', kind: 'creature', hp: 40, value: 12, printRun: 22000 },
  { num: 46, name: 'Charmander', type: 'fire', rarity: 'common', kind: 'creature', hp: 50, value: 32, printRun: 22000 },
  { num: 47, name: 'Diglett', type: 'fighting', rarity: 'common', kind: 'creature', hp: 30, value: 12, printRun: 22000 },
  { num: 48, name: 'Doduo', type: 'colorless', rarity: 'common', kind: 'creature', hp: 50, value: 10, printRun: 22000 },
  { num: 49, name: 'Drowzee', type: 'psychic', rarity: 'common', kind: 'creature', hp: 50, value: 12, printRun: 22000 },
  { num: 50, name: 'Gastly', type: 'psychic', rarity: 'common', kind: 'creature', hp: 30, value: 14, printRun: 22000 },
  { num: 51, name: 'Koffing', type: 'grass', rarity: 'common', kind: 'creature', hp: 50, value: 12, printRun: 22000 },
  { num: 52, name: 'Machop', type: 'fighting', rarity: 'common', kind: 'creature', hp: 50, value: 14, printRun: 22000 },
  { num: 53, name: 'Magnemite', type: 'lightning', rarity: 'common', kind: 'creature', hp: 40, value: 12, printRun: 22000 },
  { num: 54, name: 'Metapod', type: 'grass', rarity: 'common', kind: 'creature', hp: 70, value: 12, printRun: 22000 },
  { num: 55, name: 'Nidoran M', type: 'grass', rarity: 'common', kind: 'creature', hp: 40, value: 12, printRun: 22000 },
  { num: 56, name: 'Onix', type: 'fighting', rarity: 'common', kind: 'creature', hp: 90, value: 14, printRun: 22000 },
  { num: 57, name: 'Pidgey', type: 'colorless', rarity: 'common', kind: 'creature', hp: 40, value: 12, printRun: 22000 },
  { num: 58, name: 'Pikachu', type: 'lightning', rarity: 'common', kind: 'creature', hp: 40, value: 48, printRun: 22000 },
  { num: 59, name: 'Poliwag', type: 'water', rarity: 'common', kind: 'creature', hp: 40, value: 12, printRun: 22000 },
  { num: 60, name: 'Ponyta', type: 'fire', rarity: 'common', kind: 'creature', hp: 40, value: 14, printRun: 22000 },
  { num: 61, name: 'Rattata', type: 'colorless', rarity: 'common', kind: 'creature', hp: 30, value: 12, printRun: 22000 },
  { num: 62, name: 'Sandshrew', type: 'fighting', rarity: 'common', kind: 'creature', hp: 40, value: 12, printRun: 22000 },
  { num: 63, name: 'Squirtle', type: 'water', rarity: 'common', kind: 'creature', hp: 40, value: 30, printRun: 22000 },
  { num: 64, name: 'Starmie', type: 'water', rarity: 'common', kind: 'creature', hp: 60, value: 12, printRun: 22000 },
  { num: 65, name: 'Staryu', type: 'water', rarity: 'common', kind: 'creature', hp: 40, value: 12, printRun: 22000 },
  { num: 66, name: 'Tangela', type: 'grass', rarity: 'common', kind: 'creature', hp: 50, value: 12, printRun: 22000 },
  { num: 67, name: 'Voltorb', type: 'lightning', rarity: 'common', kind: 'creature', hp: 40, value: 12, printRun: 22000 },
  { num: 68, name: 'Vulpix', type: 'fire', rarity: 'common', kind: 'creature', hp: 50, value: 16, printRun: 22000 },
  { num: 69, name: 'Weedle', type: 'grass', rarity: 'common', kind: 'creature', hp: 40, value: 12, printRun: 22000 },
  { num: 70, name: 'Clefairy Doll', type: 'trainer', rarity: 'rare', kind: 'trainer', hp: null, value: 30, printRun: 10000 },
  { num: 71, name: 'Computer Search', type: 'trainer', rarity: 'rare', kind: 'trainer', hp: null, value: 60, printRun: 10000 },
  { num: 72, name: 'Devolution Spray', type: 'trainer', rarity: 'rare', kind: 'trainer', hp: null, value: 25, printRun: 10000 },
  { num: 73, name: 'Impostor Professor Oak', type: 'trainer', rarity: 'rare', kind: 'trainer', hp: null, value: 30, printRun: 10000 },
  { num: 74, name: 'Item Finder', type: 'trainer', rarity: 'rare', kind: 'trainer', hp: null, value: 50, printRun: 10000 },
  { num: 75, name: 'Lass', type: 'trainer', rarity: 'rare', kind: 'trainer', hp: null, value: 45, printRun: 10000 },
  { num: 76, name: 'Pokemon Breeder', type: 'trainer', rarity: 'rare', kind: 'trainer', hp: null, value: 40, printRun: 10000 },
  { num: 77, name: 'Pokemon Trader', type: 'trainer', rarity: 'rare', kind: 'trainer', hp: null, value: 35, printRun: 10000 },
  { num: 78, name: 'Scoop Up', type: 'trainer', rarity: 'rare', kind: 'trainer', hp: null, value: 30, printRun: 10000 },
  { num: 79, name: 'Super Energy Removal', type: 'trainer', rarity: 'rare', kind: 'trainer', hp: null, value: 30, printRun: 10000 },
  { num: 80, name: 'Defender', type: 'trainer', rarity: 'uncommon', kind: 'trainer', hp: null, value: 12, printRun: 30000 },
  { num: 81, name: 'Energy Retrieval', type: 'trainer', rarity: 'uncommon', kind: 'trainer', hp: null, value: 12, printRun: 30000 },
  { num: 82, name: 'Full Heal', type: 'trainer', rarity: 'uncommon', kind: 'trainer', hp: null, value: 10, printRun: 30000 },
  { num: 83, name: 'Maintenance', type: 'trainer', rarity: 'uncommon', kind: 'trainer', hp: null, value: 10, printRun: 30000 },
  { num: 84, name: 'PlusPower', type: 'trainer', rarity: 'uncommon', kind: 'trainer', hp: null, value: 14, printRun: 30000 },
  { num: 85, name: 'Pokemon Center', type: 'trainer', rarity: 'uncommon', kind: 'trainer', hp: null, value: 12, printRun: 30000 },
  { num: 86, name: 'Pokemon Flute', type: 'trainer', rarity: 'uncommon', kind: 'trainer', hp: null, value: 14, printRun: 30000 },
  { num: 87, name: 'Pokedex', type: 'trainer', rarity: 'uncommon', kind: 'trainer', hp: null, value: 12, printRun: 30000 },
  { num: 88, name: 'Professor Oak', type: 'trainer', rarity: 'uncommon', kind: 'trainer', hp: null, value: 25, printRun: 30000 },
  { num: 89, name: 'Revive', type: 'trainer', rarity: 'uncommon', kind: 'trainer', hp: null, value: 12, printRun: 30000 },
  { num: 90, name: 'Super Potion', type: 'trainer', rarity: 'uncommon', kind: 'trainer', hp: null, value: 12, printRun: 30000 },
  { num: 91, name: 'Bill', type: 'trainer', rarity: 'common', kind: 'trainer', hp: null, value: 10, printRun: 44000 },
  { num: 92, name: 'Energy Removal', type: 'trainer', rarity: 'common', kind: 'trainer', hp: null, value: 9, printRun: 44000 },
  { num: 93, name: 'Gust of Wind', type: 'trainer', rarity: 'common', kind: 'trainer', hp: null, value: 10, printRun: 44000 },
  { num: 94, name: 'Potion', type: 'trainer', rarity: 'common', kind: 'trainer', hp: null, value: 8, printRun: 44000 },
  { num: 95, name: 'Switch', type: 'trainer', rarity: 'common', kind: 'trainer', hp: null, value: 9, printRun: 44000 },
  { num: 96, name: 'Double Colorless Energy', type: 'colorless', rarity: 'uncommon', kind: 'energy', hp: null, value: 40, printRun: 60000 },
  { num: 97, name: 'Fighting Energy', type: 'fighting', rarity: 'common', kind: 'energy', hp: null, value: 6, printRun: 60000 },
  { num: 98, name: 'Fire Energy', type: 'fire', rarity: 'common', kind: 'energy', hp: null, value: 8, printRun: 60000 },
  { num: 99, name: 'Grass Energy', type: 'grass', rarity: 'common', kind: 'energy', hp: null, value: 7, printRun: 60000 },
  { num: 100, name: 'Lightning Energy', type: 'lightning', rarity: 'common', kind: 'energy', hp: null, value: 8, printRun: 60000 },
  { num: 101, name: 'Psychic Energy', type: 'psychic', rarity: 'common', kind: 'energy', hp: null, value: 7, printRun: 60000 },
  { num: 102, name: 'Water Energy', type: 'water', rarity: 'common', kind: 'energy', hp: null, value: 7, printRun: 60000 },
    ],
  },
  {
    id: 'tcg-151', name: 'Pokemon 151', year: 2023, size: 165,
    packPrice: 5, boxPrice: 160,
    cards: [
  { num: 1, name: 'Bulbasaur', type: 'grass', rarity: 'common', kind: 'creature', hp: null, value: 0.15, printRun: 220000 },
  { num: 2, name: 'Ivysaur', type: 'grass', rarity: 'rare', kind: 'creature', hp: null, value: 0.8, printRun: 90000 },
  { num: 3, name: 'Venusaur', type: 'grass', rarity: 'holo', kind: 'creature', hp: null, value: 6.0, printRun: 2500 },
  { num: 4, name: 'Charmander', type: 'fire', rarity: 'common', kind: 'creature', hp: null, value: 0.15, printRun: 220000 },
  { num: 5, name: 'Charmeleon', type: 'fire', rarity: 'rare', kind: 'creature', hp: null, value: 0.8, printRun: 90000 },
  { num: 6, name: 'Charizard', type: 'fire', rarity: 'holo', kind: 'creature', hp: null, value: 25.0, printRun: 2500 },
  { num: 7, name: 'Squirtle', type: 'water', rarity: 'common', kind: 'creature', hp: null, value: 0.15, printRun: 220000 },
  { num: 8, name: 'Wartortle', type: 'water', rarity: 'rare', kind: 'creature', hp: null, value: 0.8, printRun: 90000 },
  { num: 9, name: 'Blastoise', type: 'water', rarity: 'holo', kind: 'creature', hp: null, value: 8.0, printRun: 2500 },
  { num: 10, name: 'Caterpie', type: 'grass', rarity: 'common', kind: 'creature', hp: null, value: 0.15, printRun: 220000 },
  { num: 11, name: 'Metapod', type: 'grass', rarity: 'common', kind: 'creature', hp: null, value: 0.15, printRun: 220000 },
  { num: 12, name: 'Butterfree', type: 'grass', rarity: 'holo', kind: 'creature', hp: null, value: 2.5, printRun: 40000 },
  { num: 13, name: 'Weedle', type: 'grass', rarity: 'common', kind: 'creature', hp: null, value: 0.15, printRun: 220000 },
  { num: 14, name: 'Kakuna', type: 'grass', rarity: 'common', kind: 'creature', hp: null, value: 0.15, printRun: 220000 },
  { num: 15, name: 'Beedrill', type: 'grass', rarity: 'uncommon', kind: 'creature', hp: null, value: 0.3, printRun: 160000 },
  { num: 16, name: 'Pidgey', type: 'colorless', rarity: 'common', kind: 'creature', hp: null, value: 0.15, printRun: 220000 },
  { num: 17, name: 'Pidgeotto', type: 'colorless', rarity: 'rare', kind: 'creature', hp: null, value: 0.8, printRun: 90000 },
  { num: 18, name: 'Pidgeot', type: 'colorless', rarity: 'holo', kind: 'creature', hp: null, value: 2.5, printRun: 40000 },
  { num: 19, name: 'Rattata', type: 'colorless', rarity: 'common', kind: 'creature', hp: null, value: 0.15, printRun: 220000 },
  { num: 20, name: 'Raticate', type: 'colorless', rarity: 'common', kind: 'creature', hp: null, value: 0.15, printRun: 220000 },
  { num: 21, name: 'Spearow', type: 'colorless', rarity: 'uncommon', kind: 'creature', hp: null, value: 0.3, printRun: 160000 },
  { num: 22, name: 'Fearow', type: 'colorless', rarity: 'common', kind: 'creature', hp: null, value: 0.15, printRun: 220000 },
  { num: 23, name: 'Ekans', type: 'grass', rarity: 'common', kind: 'creature', hp: null, value: 0.15, printRun: 220000 },
  { num: 24, name: 'Arbok', type: 'grass', rarity: 'uncommon', kind: 'creature', hp: null, value: 0.3, printRun: 160000 },
  { num: 25, name: 'Pikachu', type: 'lightning', rarity: 'common', kind: 'creature', hp: null, value: 0.15, printRun: 220000 },
  { num: 26, name: 'Raichu', type: 'lightning', rarity: 'holo', kind: 'creature', hp: null, value: 2.5, printRun: 40000 },
  { num: 27, name: 'Sandshrew', type: 'fighting', rarity: 'uncommon', kind: 'creature', hp: null, value: 0.3, printRun: 160000 },
  { num: 28, name: 'Sandslash', type: 'fighting', rarity: 'rare', kind: 'creature', hp: null, value: 0.8, printRun: 90000 },
  { num: 29, name: 'Nidoran F', type: 'grass', rarity: 'common', kind: 'creature', hp: null, value: 0.15, printRun: 220000 },
  { num: 30, name: 'Nidorina', type: 'grass', rarity: 'rare', kind: 'creature', hp: null, value: 0.8, printRun: 90000 },
  { num: 31, name: 'Nidoqueen', type: 'grass', rarity: 'holo', kind: 'creature', hp: null, value: 2.5, printRun: 40000 },
  { num: 32, name: 'Nidoran M', type: 'grass', rarity: 'common', kind: 'creature', hp: null, value: 0.15, printRun: 220000 },
  { num: 33, name: 'Nidorino', type: 'grass', rarity: 'rare', kind: 'creature', hp: null, value: 0.8, printRun: 90000 },
  { num: 34, name: 'Nidoking', type: 'grass', rarity: 'holo', kind: 'creature', hp: null, value: 2.5, printRun: 40000 },
  { num: 35, name: 'Clefairy', type: 'colorless', rarity: 'common', kind: 'creature', hp: null, value: 0.15, printRun: 220000 },
  { num: 36, name: 'Clefable', type: 'colorless', rarity: 'holo', kind: 'creature', hp: null, value: 2.5, printRun: 40000 },
  { num: 37, name: 'Vulpix', type: 'fire', rarity: 'common', kind: 'creature', hp: null, value: 0.15, printRun: 220000 },
  { num: 38, name: 'Ninetales', type: 'fire', rarity: 'holo', kind: 'creature', hp: null, value: 2.5, printRun: 40000 },
  { num: 39, name: 'Jigglypuff', type: 'colorless', rarity: 'uncommon', kind: 'creature', hp: null, value: 0.3, printRun: 160000 },
  { num: 40, name: 'Wigglytuff', type: 'colorless', rarity: 'common', kind: 'creature', hp: null, value: 0.15, printRun: 220000 },
  { num: 41, name: 'Zubat', type: 'grass', rarity: 'common', kind: 'creature', hp: null, value: 0.15, printRun: 220000 },
  { num: 42, name: 'Golbat', type: 'grass', rarity: 'uncommon', kind: 'creature', hp: null, value: 0.3, printRun: 160000 },
  { num: 43, name: 'Oddish', type: 'grass', rarity: 'common', kind: 'creature', hp: null, value: 0.15, printRun: 220000 },
  { num: 44, name: 'Gloom', type: 'grass', rarity: 'rare', kind: 'creature', hp: null, value: 0.8, printRun: 90000 },
  { num: 45, name: 'Vileplume', type: 'grass', rarity: 'holo', kind: 'creature', hp: null, value: 2.5, printRun: 40000 },
  { num: 46, name: 'Paras', type: 'grass', rarity: 'common', kind: 'creature', hp: null, value: 0.15, printRun: 220000 },
  { num: 47, name: 'Parasect', type: 'grass', rarity: 'common', kind: 'creature', hp: null, value: 0.15, printRun: 220000 },
  { num: 48, name: 'Venonat', type: 'grass', rarity: 'uncommon', kind: 'creature', hp: null, value: 0.3, printRun: 160000 },
  { num: 49, name: 'Venomoth', type: 'grass', rarity: 'common', kind: 'creature', hp: null, value: 0.15, printRun: 220000 },
  { num: 50, name: 'Diglett', type: 'fighting', rarity: 'common', kind: 'creature', hp: null, value: 0.15, printRun: 220000 },
  { num: 51, name: 'Dugtrio', type: 'fighting', rarity: 'uncommon', kind: 'creature', hp: null, value: 0.3, printRun: 160000 },
  { num: 52, name: 'Meowth', type: 'colorless', rarity: 'common', kind: 'creature', hp: null, value: 0.15, printRun: 220000 },
  { num: 53, name: 'Persian', type: 'colorless', rarity: 'common', kind: 'creature', hp: null, value: 0.15, printRun: 220000 },
  { num: 54, name: 'Psyduck', type: 'water', rarity: 'uncommon', kind: 'creature', hp: null, value: 0.3, printRun: 160000 },
  { num: 55, name: 'Golduck', type: 'water', rarity: 'rare', kind: 'creature', hp: null, value: 0.8, printRun: 90000 },
  { num: 56, name: 'Mankey', type: 'fighting', rarity: 'common', kind: 'creature', hp: null, value: 0.15, printRun: 220000 },
  { num: 57, name: 'Primeape', type: 'fighting', rarity: 'rare', kind: 'creature', hp: null, value: 0.8, printRun: 90000 },
  { num: 58, name: 'Growlithe', type: 'fire', rarity: 'common', kind: 'creature', hp: null, value: 0.15, printRun: 220000 },
  { num: 59, name: 'Arcanine', type: 'fire', rarity: 'holo', kind: 'creature', hp: null, value: 2.5, printRun: 40000 },
  { num: 60, name: 'Poliwag', type: 'water', rarity: 'uncommon', kind: 'creature', hp: null, value: 0.3, printRun: 160000 },
  { num: 61, name: 'Poliwhirl', type: 'water', rarity: 'rare', kind: 'creature', hp: null, value: 0.8, printRun: 90000 },
  { num: 62, name: 'Poliwrath', type: 'water', rarity: 'holo', kind: 'creature', hp: null, value: 2.5, printRun: 40000 },
  { num: 63, name: 'Abra', type: 'psychic', rarity: 'uncommon', kind: 'creature', hp: null, value: 0.3, printRun: 160000 },
  { num: 64, name: 'Kadabra', type: 'psychic', rarity: 'rare', kind: 'creature', hp: null, value: 0.8, printRun: 90000 },
  { num: 65, name: 'Alakazam', type: 'psychic', rarity: 'holo', kind: 'creature', hp: null, value: 3.5, printRun: 2500 },
  { num: 66, name: 'Machop', type: 'fighting', rarity: 'uncommon', kind: 'creature', hp: null, value: 0.3, printRun: 160000 },
  { num: 67, name: 'Machoke', type: 'fighting', rarity: 'rare', kind: 'creature', hp: null, value: 0.8, printRun: 90000 },
  { num: 68, name: 'Machamp', type: 'fighting', rarity: 'holo', kind: 'creature', hp: null, value: 2.5, printRun: 40000 },
  { num: 69, name: 'Bellsprout', type: 'grass', rarity: 'uncommon', kind: 'creature', hp: null, value: 0.3, printRun: 160000 },
  { num: 70, name: 'Weepinbell', type: 'grass', rarity: 'rare', kind: 'creature', hp: null, value: 0.8, printRun: 90000 },
  { num: 71, name: 'Victreebel', type: 'grass', rarity: 'holo', kind: 'creature', hp: null, value: 2.5, printRun: 40000 },
  { num: 72, name: 'Tentacool', type: 'water', rarity: 'uncommon', kind: 'creature', hp: null, value: 0.3, printRun: 160000 },
  { num: 73, name: 'Tentacruel', type: 'water', rarity: 'common', kind: 'creature', hp: null, value: 0.15, printRun: 220000 },
  { num: 74, name: 'Geodude', type: 'fighting', rarity: 'common', kind: 'creature', hp: null, value: 0.15, printRun: 220000 },
  { num: 75, name: 'Graveler', type: 'fighting', rarity: 'rare', kind: 'creature', hp: null, value: 0.8, printRun: 90000 },
  { num: 76, name: 'Golem', type: 'fighting', rarity: 'holo', kind: 'creature', hp: null, value: 2.5, printRun: 40000 },
  { num: 77, name: 'Ponyta', type: 'fire', rarity: 'common', kind: 'creature', hp: null, value: 0.15, printRun: 220000 },
  { num: 78, name: 'Rapidash', type: 'fire', rarity: 'holo', kind: 'creature', hp: null, value: 2.5, printRun: 40000 },
  { num: 79, name: 'Slowpoke', type: 'psychic', rarity: 'common', kind: 'creature', hp: null, value: 0.15, printRun: 220000 },
  { num: 80, name: 'Slowbro', type: 'psychic', rarity: 'rare', kind: 'creature', hp: null, value: 0.8, printRun: 90000 },
  { num: 81, name: 'Magnemite', type: 'lightning', rarity: 'uncommon', kind: 'creature', hp: null, value: 0.3, printRun: 160000 },
  { num: 82, name: 'Magneton', type: 'lightning', rarity: 'rare', kind: 'creature', hp: null, value: 0.8, printRun: 90000 },
  { num: 83, name: 'Farfetch\'d', type: 'colorless', rarity: 'common', kind: 'creature', hp: null, value: 0.15, printRun: 220000 },
  { num: 84, name: 'Doduo', type: 'colorless', rarity: 'uncommon', kind: 'creature', hp: null, value: 0.3, printRun: 160000 },
  { num: 85, name: 'Dodrio', type: 'colorless', rarity: 'common', kind: 'creature', hp: null, value: 0.15, printRun: 220000 },
  { num: 86, name: 'Seel', type: 'water', rarity: 'common', kind: 'creature', hp: null, value: 0.15, printRun: 220000 },
  { num: 87, name: 'Dewgong', type: 'water', rarity: 'rare', kind: 'creature', hp: null, value: 0.8, printRun: 90000 },
  { num: 88, name: 'Grimer', type: 'grass', rarity: 'common', kind: 'creature', hp: null, value: 0.15, printRun: 220000 },
  { num: 89, name: 'Muk', type: 'grass', rarity: 'holo', kind: 'creature', hp: null, value: 2.5, printRun: 40000 },
  { num: 90, name: 'Shellder', type: 'water', rarity: 'uncommon', kind: 'creature', hp: null, value: 0.3, printRun: 160000 },
  { num: 91, name: 'Cloyster', type: 'water', rarity: 'rare', kind: 'creature', hp: null, value: 0.8, printRun: 90000 },
  { num: 92, name: 'Gastly', type: 'psychic', rarity: 'common', kind: 'creature', hp: null, value: 0.15, printRun: 220000 },
  { num: 93, name: 'Haunter', type: 'psychic', rarity: 'rare', kind: 'creature', hp: null, value: 0.8, printRun: 90000 },
  { num: 94, name: 'Gengar', type: 'psychic', rarity: 'holo', kind: 'creature', hp: null, value: 4.0, printRun: 2500 },
  { num: 95, name: 'Onix', type: 'fighting', rarity: 'common', kind: 'creature', hp: null, value: 0.15, printRun: 220000 },
  { num: 96, name: 'Drowzee', type: 'psychic', rarity: 'uncommon', kind: 'creature', hp: null, value: 0.3, printRun: 160000 },
  { num: 97, name: 'Hypno', type: 'psychic', rarity: 'rare', kind: 'creature', hp: null, value: 0.8, printRun: 90000 },
  { num: 98, name: 'Krabby', type: 'water', rarity: 'common', kind: 'creature', hp: null, value: 0.15, printRun: 220000 },
  { num: 99, name: 'Kingler', type: 'water', rarity: 'rare', kind: 'creature', hp: null, value: 0.8, printRun: 90000 },
  { num: 100, name: 'Voltorb', type: 'lightning', rarity: 'common', kind: 'creature', hp: null, value: 0.15, printRun: 220000 },
  { num: 101, name: 'Electrode', type: 'lightning', rarity: 'rare', kind: 'creature', hp: null, value: 0.8, printRun: 90000 },
  { num: 102, name: 'Exeggcute', type: 'grass', rarity: 'uncommon', kind: 'creature', hp: null, value: 0.3, printRun: 160000 },
  { num: 103, name: 'Exeggutor', type: 'grass', rarity: 'holo', kind: 'creature', hp: null, value: 2.5, printRun: 40000 },
  { num: 104, name: 'Cubone', type: 'fighting', rarity: 'common', kind: 'creature', hp: null, value: 0.15, printRun: 220000 },
  { num: 105, name: 'Marowak', type: 'fighting', rarity: 'rare', kind: 'creature', hp: null, value: 0.8, printRun: 90000 },
  { num: 106, name: 'Hitmonlee', type: 'fighting', rarity: 'rare', kind: 'creature', hp: null, value: 0.8, printRun: 90000 },
  { num: 107, name: 'Hitmonchan', type: 'fighting', rarity: 'rare', kind: 'creature', hp: null, value: 0.8, printRun: 90000 },
  { num: 108, name: 'Lickitung', type: 'colorless', rarity: 'uncommon', kind: 'creature', hp: null, value: 0.3, printRun: 160000 },
  { num: 109, name: 'Koffing', type: 'grass', rarity: 'common', kind: 'creature', hp: null, value: 0.15, printRun: 220000 },
  { num: 110, name: 'Weezing', type: 'grass', rarity: 'rare', kind: 'creature', hp: null, value: 0.8, printRun: 90000 },
  { num: 111, name: 'Rhyhorn', type: 'fighting', rarity: 'uncommon', kind: 'creature', hp: null, value: 0.3, printRun: 160000 },
  { num: 112, name: 'Rhydon', type: 'fighting', rarity: 'holo', kind: 'creature', hp: null, value: 2.5, printRun: 40000 },
  { num: 113, name: 'Chansey', type: 'colorless', rarity: 'rare', kind: 'creature', hp: null, value: 0.8, printRun: 90000 },
  { num: 114, name: 'Tangela', type: 'grass', rarity: 'uncommon', kind: 'creature', hp: null, value: 0.3, printRun: 160000 },
  { num: 115, name: 'Kangaskhan', type: 'colorless', rarity: 'holo', kind: 'creature', hp: null, value: 2.5, printRun: 40000 },
  { num: 116, name: 'Horsea', type: 'water', rarity: 'common', kind: 'creature', hp: null, value: 0.15, printRun: 220000 },
  { num: 117, name: 'Seadra', type: 'water', rarity: 'rare', kind: 'creature', hp: null, value: 0.8, printRun: 90000 },
  { num: 118, name: 'Goldeen', type: 'water', rarity: 'common', kind: 'creature', hp: null, value: 0.15, printRun: 220000 },
  { num: 119, name: 'Seaking', type: 'water', rarity: 'rare', kind: 'creature', hp: null, value: 0.8, printRun: 90000 },
  { num: 120, name: 'Staryu', type: 'water', rarity: 'uncommon', kind: 'creature', hp: null, value: 0.3, printRun: 160000 },
  { num: 121, name: 'Starmie', type: 'water', rarity: 'holo', kind: 'creature', hp: null, value: 2.5, printRun: 40000 },
  { num: 122, name: 'Mr. Mime', type: 'psychic', rarity: 'rare', kind: 'creature', hp: null, value: 0.8, printRun: 90000 },
  { num: 123, name: 'Scyther', type: 'grass', rarity: 'holo', kind: 'creature', hp: null, value: 2.5, printRun: 40000 },
  { num: 124, name: 'Jynx', type: 'psychic', rarity: 'holo', kind: 'creature', hp: null, value: 2.5, printRun: 40000 },
  { num: 125, name: 'Electabuzz', type: 'lightning', rarity: 'holo', kind: 'creature', hp: null, value: 2.5, printRun: 40000 },
  { num: 126, name: 'Magmar', type: 'fire', rarity: 'holo', kind: 'creature', hp: null, value: 2.5, printRun: 40000 },
  { num: 127, name: 'Pinsir', type: 'grass', rarity: 'holo', kind: 'creature', hp: null, value: 2.5, printRun: 40000 },
  { num: 128, name: 'Tauros', type: 'colorless', rarity: 'rare', kind: 'creature', hp: null, value: 0.8, printRun: 90000 },
  { num: 129, name: 'Magikarp', type: 'water', rarity: 'uncommon', kind: 'creature', hp: null, value: 0.3, printRun: 160000 },
  { num: 130, name: 'Gyarados', type: 'water', rarity: 'holo', kind: 'creature', hp: null, value: 2.5, printRun: 40000 },
  { num: 131, name: 'Lapras', type: 'water', rarity: 'holo', kind: 'creature', hp: null, value: 2.5, printRun: 40000 },
  { num: 132, name: 'Ditto', type: 'colorless', rarity: 'uncommon', kind: 'creature', hp: null, value: 0.3, printRun: 160000 },
  { num: 133, name: 'Eevee', type: 'colorless', rarity: 'rare', kind: 'creature', hp: null, value: 0.8, printRun: 90000 },
  { num: 134, name: 'Vaporeon', type: 'water', rarity: 'holo', kind: 'creature', hp: null, value: 2.5, printRun: 40000 },
  { num: 135, name: 'Jolteon', type: 'lightning', rarity: 'holo', kind: 'creature', hp: null, value: 2.5, printRun: 40000 },
  { num: 136, name: 'Flareon', type: 'fire', rarity: 'holo', kind: 'creature', hp: null, value: 2.5, printRun: 40000 },
  { num: 137, name: 'Porygon', type: 'colorless', rarity: 'rare', kind: 'creature', hp: null, value: 0.8, printRun: 90000 },
  { num: 138, name: 'Omanyte', type: 'water', rarity: 'uncommon', kind: 'creature', hp: null, value: 0.3, printRun: 160000 },
  { num: 139, name: 'Omastar', type: 'water', rarity: 'rare', kind: 'creature', hp: null, value: 0.8, printRun: 90000 },
  { num: 140, name: 'Kabuto', type: 'fighting', rarity: 'common', kind: 'creature', hp: null, value: 0.15, printRun: 220000 },
  { num: 141, name: 'Kabutops', type: 'fighting', rarity: 'rare', kind: 'creature', hp: null, value: 0.8, printRun: 90000 },
  { num: 142, name: 'Aerodactyl', type: 'fighting', rarity: 'holo', kind: 'creature', hp: null, value: 2.5, printRun: 40000 },
  { num: 143, name: 'Snorlax', type: 'colorless', rarity: 'holo', kind: 'creature', hp: null, value: 2.5, printRun: 40000 },
  { num: 144, name: 'Articuno', type: 'water', rarity: 'holo', kind: 'creature', hp: null, value: 2.5, printRun: 40000 },
  { num: 145, name: 'Zapdos', type: 'lightning', rarity: 'holo', kind: 'creature', hp: null, value: 4.0, printRun: 2500 },
  { num: 146, name: 'Moltres', type: 'fire', rarity: 'holo', kind: 'creature', hp: null, value: 2.5, printRun: 40000 },
  { num: 147, name: 'Dratini', type: 'colorless', rarity: 'rare', kind: 'creature', hp: null, value: 0.8, printRun: 90000 },
  { num: 148, name: 'Dragonair', type: 'colorless', rarity: 'rare', kind: 'creature', hp: null, value: 0.8, printRun: 90000 },
  { num: 149, name: 'Dragonite', type: 'colorless', rarity: 'holo', kind: 'creature', hp: null, value: 2.5, printRun: 40000 },
  { num: 150, name: 'Mewtwo', type: 'psychic', rarity: 'holo', kind: 'creature', hp: null, value: 2.5, printRun: 40000 },
  { num: 151, name: 'Mew', type: 'psychic', rarity: 'holo', kind: 'creature', hp: null, value: 8.0, printRun: 2500 },
  { num: 199, name: 'Charizard ex', type: 'fire', rarity: 'chase', kind: 'creature', hp: null, value: 240.0, printRun: 900, outOf: 165 },
    ],
  },
  {
    // The money game: history's currency as chase cardboard. `type` carries
    // the engraving subject class for the banknote renderer.
    id: 'tcg-currency', name: 'Currency — Series 1', year: 2024, size: 50,
    packPrice: 12, boxPrice: 220,
    cards: [
  { num: 1, name: 'One Dollar Bill', type: 'note', rarity: 'common', kind: 'artifact', hp: null, value: 1.5, printRun: 90000 },
  { num: 2, name: 'Five Dollar Bill', type: 'note', rarity: 'common', kind: 'artifact', hp: null, value: 1.5, printRun: 90000 },
  { num: 3, name: 'Ten Dollar Bill', type: 'note', rarity: 'common', kind: 'artifact', hp: null, value: 1.5, printRun: 90000 },
  { num: 4, name: 'Twenty Dollar Bill', type: 'note', rarity: 'common', kind: 'artifact', hp: null, value: 2, printRun: 90000 },
  { num: 5, name: 'Fifty Dollar Bill', type: 'note', rarity: 'common', kind: 'artifact', hp: null, value: 2, printRun: 90000 },
  { num: 6, name: 'Hundred Dollar Bill', type: 'note', rarity: 'common', kind: 'artifact', hp: null, value: 3, printRun: 90000 },
  { num: 7, name: 'Japanese Yen', type: 'note', rarity: 'common', kind: 'artifact', hp: null, value: 1, printRun: 90000 },
  { num: 8, name: 'British Pound', type: 'note', rarity: 'common', kind: 'artifact', hp: null, value: 1, printRun: 90000 },
  { num: 9, name: 'Euro Note', type: 'note', rarity: 'common', kind: 'artifact', hp: null, value: 1, printRun: 90000 },
  { num: 10, name: 'Swiss Franc', type: 'note', rarity: 'common', kind: 'artifact', hp: null, value: 1.5, printRun: 90000 },
  { num: 11, name: 'Wheat Penny', type: 'coin', rarity: 'common', kind: 'artifact', hp: null, value: 1, printRun: 90000 },
  { num: 12, name: 'Buffalo Nickel', type: 'coin', rarity: 'common', kind: 'artifact', hp: null, value: 1.5, printRun: 90000 },
  { num: 13, name: 'Mercury Dime', type: 'coin', rarity: 'common', kind: 'artifact', hp: null, value: 1.5, printRun: 90000 },
  { num: 14, name: 'Standing Liberty Quarter', type: 'coin', rarity: 'common', kind: 'artifact', hp: null, value: 2, printRun: 90000 },
  { num: 15, name: 'Franklin Half Dollar', type: 'coin', rarity: 'common', kind: 'artifact', hp: null, value: 2, printRun: 90000 },
  { num: 16, name: 'Eisenhower Dollar', type: 'coin', rarity: 'common', kind: 'artifact', hp: null, value: 2, printRun: 90000 },
  { num: 17, name: 'Canadian Maple Leaf', type: 'coin', rarity: 'common', kind: 'artifact', hp: null, value: 2, printRun: 90000 },
  { num: 18, name: 'Mexican Peso', type: 'coin', rarity: 'common', kind: 'artifact', hp: null, value: 1, printRun: 90000 },
  { num: 19, name: 'Ancient Drachma', type: 'coin', rarity: 'common', kind: 'artifact', hp: null, value: 3, printRun: 90000 },
  { num: 20, name: 'Roman Denarius', type: 'coin', rarity: 'common', kind: 'artifact', hp: null, value: 3, printRun: 90000 },
  { num: 21, name: 'Two Dollar Bill', type: 'note', rarity: 'uncommon', kind: 'artifact', hp: null, value: 5, printRun: 45000 },
  { num: 22, name: 'Silver Certificate', type: 'note', rarity: 'uncommon', kind: 'artifact', hp: null, value: 6, printRun: 45000 },
  { num: 23, name: 'Morgan Silver Dollar', type: 'coin', rarity: 'uncommon', kind: 'artifact', hp: null, value: 8, printRun: 45000 },
  { num: 24, name: 'Peace Dollar', type: 'coin', rarity: 'uncommon', kind: 'artifact', hp: null, value: 7, printRun: 45000 },
  { num: 25, name: 'American Silver Eagle', type: 'coin', rarity: 'uncommon', kind: 'artifact', hp: null, value: 8, printRun: 45000 },
  { num: 26, name: 'Gold Krugerrand', type: 'gold', rarity: 'uncommon', kind: 'artifact', hp: null, value: 12, printRun: 45000 },
  { num: 27, name: 'Piece of Eight', type: 'coin', rarity: 'uncommon', kind: 'artifact', hp: null, value: 10, printRun: 45000 },
  { num: 28, name: 'Spanish Doubloon', type: 'gold', rarity: 'uncommon', kind: 'artifact', hp: null, value: 12, printRun: 45000 },
  { num: 29, name: 'Gold Bar — 400oz', type: 'gold', rarity: 'uncommon', kind: 'artifact', hp: null, value: 10, printRun: 45000 },
  { num: 30, name: 'The Mint Press', type: 'vault', rarity: 'uncommon', kind: 'artifact', hp: null, value: 6, printRun: 45000 },
  { num: 31, name: 'Wall Street Bull', type: 'figure', rarity: 'uncommon', kind: 'artifact', hp: null, value: 9, printRun: 45000 },
  { num: 32, name: 'Ticker Tape 1929', type: 'note', rarity: 'uncommon', kind: 'artifact', hp: null, value: 8, printRun: 45000 },
  { num: 33, name: 'Five Hundred Dollar Bill', type: 'note', rarity: 'rare', kind: 'artifact', hp: null, value: 25, printRun: 15000 },
  { num: 34, name: 'One Thousand Dollar Bill', type: 'note', rarity: 'rare', kind: 'artifact', hp: null, value: 35, printRun: 15000 },
  { num: 35, name: 'Ethereum — The Merge', type: 'crypto', rarity: 'rare', kind: 'artifact', hp: null, value: 30, printRun: 15000 },
  { num: 36, name: 'Fort Knox', type: 'vault', rarity: 'rare', kind: 'artifact', hp: null, value: 22, printRun: 15000 },
  { num: 37, name: '1804 Silver Dollar', type: 'coin', rarity: 'rare', kind: 'artifact', hp: null, value: 45, printRun: 15000 },
  { num: 38, name: '1913 Liberty Nickel', type: 'coin', rarity: 'rare', kind: 'artifact', hp: null, value: 40, printRun: 15000 },
  { num: 39, name: 'Brasher Doubloon', type: 'gold', rarity: 'rare', kind: 'artifact', hp: null, value: 50, printRun: 15000 },
  { num: 40, name: 'The Emerald Vault', type: 'gem', rarity: 'rare', kind: 'artifact', hp: null, value: 35, printRun: 15000 },
  { num: 41, name: 'The Sapphire Vault', type: 'gem', rarity: 'rare', kind: 'artifact', hp: null, value: 35, printRun: 15000 },
  { num: 42, name: 'The Ruby Vault', type: 'gem', rarity: 'rare', kind: 'artifact', hp: null, value: 38, printRun: 15000 },
  { num: 43, name: 'Ten Thousand Dollar Bill', type: 'note', rarity: 'holo', kind: 'artifact', hp: null, value: 180, printRun: 4000 },
  { num: 44, name: 'One Hundred Thousand — Gold Certificate', type: 'note', rarity: 'holo', kind: 'artifact', hp: null, value: 350, printRun: 4000 },
  { num: 45, name: '1933 Double Eagle', type: 'gold', rarity: 'holo', kind: 'artifact', hp: null, value: 600, printRun: 4000 },
  { num: 46, name: 'Bitcoin — Genesis Block', type: 'crypto', rarity: 'holo', kind: 'artifact', hp: null, value: 450, printRun: 4000 },
  { num: 47, name: 'Satoshi Nakamoto', type: 'figure', rarity: 'holo', kind: 'artifact', hp: null, value: 320, printRun: 4000 },
  { num: 48, name: 'Benjamin Franklin — Cut Signature', type: 'signature', rarity: 'holo', kind: 'artifact', hp: null, value: 1400, printRun: 2500 },
  { num: 49, name: 'Alexander Hamilton — Cut Signature', type: 'signature', rarity: 'holo', kind: 'artifact', hp: null, value: 900, printRun: 2500 },
  { num: 50, name: 'The Diamond Vault', type: 'gem', rarity: 'holo', kind: 'artifact', hp: null, value: 500, printRun: 4000 },
  { num: 51, name: '1 BTC — Redemption Vault', type: 'crypto', rarity: 'chase', kind: 'artifact', hp: null, value: 95000, printRun: 100, outOf: 50 },
    ],
  },
];

/**
 * THE VAULT — the real hobby's grail singles (research-sourced checklists
 * and market values). These sets are NEVER sold as packs: copies surface
 * one at a time on the open market. `type` carries the year+brand line
 * for display and the fallback renderer; printRun is the plausible
 * surviving population.
 */
export const VAULT_SETS: TcgSetData[] = [
  {
    id: 'tcg-vault-fb', name: 'The Vault — Football Grails', year: 2026, size: 30,
    packPrice: 0, boxPrice: 0,
    cards: [
  { num: 1, name: 'Tom Brady', type: '2000 Contenders Championship Ticket Auto', rarity: 'chase', kind: 'artifact', hp: null, value: 2500000, printRun: 100 },
  { num: 2, name: 'Bronko Nagurski', type: '1935 National Chicle', rarity: 'chase', kind: 'artifact', hp: null, value: 1500000, printRun: 80 },
  { num: 3, name: 'Patrick Mahomes', type: '2017 National Treasures RPA /99', rarity: 'chase', kind: 'artifact', hp: null, value: 350000, printRun: 99 },
  { num: 4, name: 'Tom Brady', type: '2000 Contenders Rookie Ticket Auto', rarity: 'chase', kind: 'artifact', hp: null, value: 300000, printRun: 500 },
  { num: 5, name: 'Jim Brown', type: '1958 Topps RC', rarity: 'chase', kind: 'artifact', hp: null, value: 250000, printRun: 600 },
  { num: 6, name: 'Joe Namath', type: '1965 Topps Tall Boy RC', rarity: 'chase', kind: 'artifact', hp: null, value: 200000, printRun: 500 },
  { num: 7, name: 'Johnny Unitas', type: '1957 Topps RC', rarity: 'chase', kind: 'artifact', hp: null, value: 175000, printRun: 700 },
  { num: 8, name: 'Peyton Manning', type: '1998 Contenders Rookie Ticket Auto', rarity: 'chase', kind: 'artifact', hp: null, value: 150000, printRun: 200 },
  { num: 9, name: 'Joe Burrow', type: '2020 National Treasures RPA /99', rarity: 'holo', kind: 'artifact', hp: null, value: 60000, printRun: 99 },
  { num: 10, name: 'Justin Herbert', type: '2020 National Treasures RPA /99', rarity: 'holo', kind: 'artifact', hp: null, value: 45000, printRun: 99 },
  { num: 11, name: 'Bart Starr', type: '1957 Topps RC', rarity: 'holo', kind: 'artifact', hp: null, value: 35000, printRun: 900 },
  { num: 12, name: 'Aaron Rodgers', type: '2005 Contenders Rookie Ticket Auto', rarity: 'holo', kind: 'artifact', hp: null, value: 20000, printRun: 530 },
  { num: 13, name: 'Terry Bradshaw', type: '1971 Topps RC', rarity: 'holo', kind: 'artifact', hp: null, value: 18000, printRun: 1200 },
  { num: 14, name: 'Patrick Mahomes', type: '2017 Contenders Rookie Ticket Auto', rarity: 'holo', kind: 'artifact', hp: null, value: 15000, printRun: 1000 },
  { num: 15, name: 'Gale Sayers', type: '1966 Philadelphia RC', rarity: 'holo', kind: 'artifact', hp: null, value: 15000, printRun: 1100 },
  { num: 16, name: 'Walter Payton', type: '1976 Topps RC', rarity: 'holo', kind: 'artifact', hp: null, value: 12000, printRun: 2000 },
  { num: 17, name: 'Tom Brady', type: '2000 SP Authentic /1250', rarity: 'holo', kind: 'artifact', hp: null, value: 12000, printRun: 1250 },
  { num: 18, name: 'Drew Brees', type: '2001 Contenders Rookie Ticket Auto', rarity: 'holo', kind: 'artifact', hp: null, value: 10000, printRun: 800 },
  { num: 19, name: 'Roger Staubach', type: '1972 Topps RC', rarity: 'rare', kind: 'artifact', hp: null, value: 9000, printRun: 1800 },
  { num: 20, name: 'Tom Brady', type: '2000 Bowman Chrome RC', rarity: 'rare', kind: 'artifact', hp: null, value: 7500, printRun: 2500 },
  { num: 21, name: 'Dick Butkus', type: '1966 Philadelphia RC', rarity: 'rare', kind: 'artifact', hp: null, value: 6000, printRun: 1500 },
  { num: 22, name: 'Jerry Rice', type: '1986 Topps RC', rarity: 'rare', kind: 'artifact', hp: null, value: 5000, printRun: 5000 },
  { num: 23, name: 'Patrick Mahomes', type: '2017 Prizm Silver RC', rarity: 'rare', kind: 'artifact', hp: null, value: 2500, printRun: 3000 },
  { num: 24, name: 'Joe Montana', type: '1981 Topps RC', rarity: 'rare', kind: 'artifact', hp: null, value: 2500, printRun: 6000 },
  { num: 25, name: 'Dan Marino', type: '1984 Topps RC', rarity: 'rare', kind: 'artifact', hp: null, value: 1800, printRun: 7000 },
  { num: 26, name: 'John Elway', type: '1984 Topps RC', rarity: 'rare', kind: 'artifact', hp: null, value: 1200, printRun: 7000 },
  { num: 27, name: 'Josh Allen', type: '2018 Prizm Silver RC', rarity: 'rare', kind: 'artifact', hp: null, value: 1000, printRun: 4000 },
  { num: 28, name: 'Lamar Jackson', type: '2018 Prizm Silver RC', rarity: 'rare', kind: 'artifact', hp: null, value: 800, printRun: 4000 },
  { num: 29, name: 'Justin Herbert', type: '2020 Prizm Silver RC', rarity: 'rare', kind: 'artifact', hp: null, value: 800, printRun: 5000 },
  { num: 30, name: 'Joe Burrow', type: '2020 Prizm Silver RC', rarity: 'rare', kind: 'artifact', hp: null, value: 600, printRun: 5000 },
    ],
  },
  {
    id: 'tcg-vault-bb', name: 'The Vault — Baseball Grails', year: 2026, size: 30,
    packPrice: 0, boxPrice: 0,
    cards: [
  { num: 1, name: 'Honus Wagner', type: '1909 T206 White Border', rarity: 'chase', kind: 'artifact', hp: null, value: 2500000, printRun: 60 },
  { num: 2, name: 'Babe Ruth', type: '1916 M101-5 Sporting News RC', rarity: 'chase', kind: 'artifact', hp: null, value: 250000, printRun: 120 },
  { num: 3, name: 'Mickey Mantle', type: '1952 Topps #311', rarity: 'chase', kind: 'artifact', hp: null, value: 150000, printRun: 1700 },
  { num: 4, name: 'Joe Jackson', type: '1914 Cracker Jack', rarity: 'chase', kind: 'artifact', hp: null, value: 120000, printRun: 200 },
  { num: 5, name: 'Babe Ruth', type: '1933 Goudey #53', rarity: 'chase', kind: 'artifact', hp: null, value: 50000, printRun: 1000 },
  { num: 6, name: 'Mickey Mantle', type: '1951 Bowman RC', rarity: 'holo', kind: 'artifact', hp: null, value: 30000, printRun: 1800 },
  { num: 7, name: 'Jackie Robinson', type: '1948 Leaf RC', rarity: 'holo', kind: 'artifact', hp: null, value: 20000, printRun: 1200 },
  { num: 8, name: 'Albert Pujols', type: '2001 Bowman Chrome Auto /500', rarity: 'holo', kind: 'artifact', hp: null, value: 18000, printRun: 500 },
  { num: 9, name: 'Lou Gehrig', type: '1934 Goudey #37', rarity: 'holo', kind: 'artifact', hp: null, value: 17000, printRun: 1400 },
  { num: 10, name: 'Mike Trout', type: '2009 Bowman Chrome Draft Auto', rarity: 'holo', kind: 'artifact', hp: null, value: 15000, printRun: 800 },
  { num: 11, name: 'Ty Cobb', type: '1909 T206 Red Portrait', rarity: 'holo', kind: 'artifact', hp: null, value: 14000, printRun: 900 },
  { num: 12, name: 'Joe DiMaggio', type: '1938 Goudey Heads-Up', rarity: 'holo', kind: 'artifact', hp: null, value: 12000, printRun: 1100 },
  { num: 13, name: 'Roberto Clemente', type: '1955 Topps RC', rarity: 'holo', kind: 'artifact', hp: null, value: 10000, printRun: 2200 },
  { num: 14, name: 'Hank Aaron', type: '1954 Topps RC', rarity: 'holo', kind: 'artifact', hp: null, value: 9000, printRun: 2500 },
  { num: 15, name: 'Willie Mays', type: '1952 Topps #261', rarity: 'holo', kind: 'artifact', hp: null, value: 8000, printRun: 2000 },
  { num: 16, name: 'Ted Williams', type: '1939 Play Ball RC', rarity: 'holo', kind: 'artifact', hp: null, value: 6000, printRun: 1600 },
  { num: 17, name: 'Paul Skenes', type: '2023 Bowman Chrome 1st Auto', rarity: 'holo', kind: 'artifact', hp: null, value: 4000, printRun: 700 },
  { num: 18, name: 'Shohei Ohtani', type: '2018 Bowman Chrome Auto RC', rarity: 'rare', kind: 'artifact', hp: null, value: 2500, printRun: 1200 },
  { num: 19, name: 'Sandy Koufax', type: '1955 Topps RC', rarity: 'rare', kind: 'artifact', hp: null, value: 2400, printRun: 2600 },
  { num: 20, name: 'Ichiro Suzuki', type: '2001 SP Authentic Auto /900', rarity: 'rare', kind: 'artifact', hp: null, value: 2000, printRun: 900 },
  { num: 21, name: 'Nolan Ryan', type: '1968 Topps RC', rarity: 'rare', kind: 'artifact', hp: null, value: 1900, printRun: 4000 },
  { num: 22, name: 'Pete Rose', type: '1963 Topps RC', rarity: 'rare', kind: 'artifact', hp: null, value: 1800, printRun: 3200 },
  { num: 23, name: 'Bryce Harper', type: '2011 Bowman Chrome Auto', rarity: 'rare', kind: 'artifact', hp: null, value: 1200, printRun: 1500 },
  { num: 24, name: 'Reggie Jackson', type: '1969 Topps RC', rarity: 'rare', kind: 'artifact', hp: null, value: 1100, printRun: 4500 },
  { num: 25, name: 'Mike Trout', type: '2011 Topps Update RC', rarity: 'rare', kind: 'artifact', hp: null, value: 900, printRun: 9000 },
  { num: 26, name: 'Derek Jeter', type: '1993 SP Foil RC', rarity: 'rare', kind: 'artifact', hp: null, value: 700, printRun: 8000 },
  { num: 27, name: 'Rickey Henderson', type: '1980 Topps RC', rarity: 'rare', kind: 'artifact', hp: null, value: 400, printRun: 12000 },
  { num: 28, name: 'Alex Rodriguez', type: '1994 SP Foil RC', rarity: 'rare', kind: 'artifact', hp: null, value: 250, printRun: 10000 },
  { num: 29, name: 'Shohei Ohtani', type: '2018 Topps Update RC', rarity: 'rare', kind: 'artifact', hp: null, value: 150, printRun: 20000 },
  { num: 30, name: 'Ken Griffey Jr.', type: '1989 Upper Deck #1', rarity: 'rare', kind: 'artifact', hp: null, value: 100, printRun: 30000 },
    ],
  },
];
