/**
 * TCG concept data — checklists, authored raw near-mint values, and print
 * runs for the two collectible sets. Generated from presets/pokemon-concept
 * .json; values are honest market ballparks (Base Set priced as 1st
 * Edition vintage, 151 priced as modern retail with its ex/secret chase).
 * Pure data: the engine builds populations and packs from this.
 */

export interface TcgCardData {
  num: number;
  name: string;
  type: string;
  rarity: 'common' | 'uncommon' | 'rare' | 'holo' | 'chase';
  kind: 'creature' | 'trainer' | 'energy';
  /** Raw near-mint market value, USD. */
  value: number;
  hp: number | null;
  printRun: number;
  /** Display denominator when it differs from the set size (secret rares). */
  outOf?: number;
}

export interface TcgSetData {
  id: string;
  name: string;
  year: number;
  size: number;
  /** Booster structure. */
  packPrice: number;
  boxPrice: number;
  cards: TcgCardData[];
}

export const TCG_SETS: TcgSetData[] = [
  {
    id: 'tcg-base', name: '1999 Base Set — 1st Edition', year: 1999, size: 102,
    packPrice: 3500, boxPrice: 110000,
    cards: [
  { num: 1, name: 'Alakazam', type: 'psychic', rarity: 'holo', kind: 'creature', hp: 80, value: 900, printRun: 3000 },
  { num: 2, name: 'Blastoise', type: 'water', rarity: 'holo', kind: 'creature', hp: 100, value: 2800, printRun: 3000 },
  { num: 3, name: 'Chansey', type: 'colorless', rarity: 'holo', kind: 'creature', hp: 120, value: 1000, printRun: 3000 },
  { num: 4, name: 'Charizard', type: 'fire', rarity: 'holo', kind: 'creature', hp: 120, value: 22000, printRun: 3000 },
  { num: 5, name: 'Clefairy', type: 'colorless', rarity: 'holo', kind: 'creature', hp: 40, value: 600, printRun: 3000 },
  { num: 6, name: 'Gyarados', type: 'water', rarity: 'holo', kind: 'creature', hp: 100, value: 800, printRun: 3000 },
  { num: 7, name: 'Hitmonchan', type: 'fighting', rarity: 'holo', kind: 'creature', hp: 70, value: 500, printRun: 3000 },
  { num: 8, name: 'Machamp', type: 'fighting', rarity: 'holo', kind: 'creature', hp: 100, value: 300, printRun: 3000 },
  { num: 9, name: 'Magneton', type: 'lightning', rarity: 'holo', kind: 'creature', hp: 60, value: 450, printRun: 3000 },
  { num: 10, name: 'Mewtwo', type: 'psychic', rarity: 'holo', kind: 'creature', hp: 60, value: 900, printRun: 3000 },
  { num: 11, name: 'Nidoking', type: 'grass', rarity: 'holo', kind: 'creature', hp: 90, value: 550, printRun: 3000 },
  { num: 12, name: 'Ninetales', type: 'fire', rarity: 'holo', kind: 'creature', hp: 80, value: 700, printRun: 3000 },
  { num: 13, name: 'Poliwrath', type: 'water', rarity: 'holo', kind: 'creature', hp: 90, value: 450, printRun: 3000 },
  { num: 14, name: 'Raichu', type: 'lightning', rarity: 'holo', kind: 'creature', hp: 80, value: 1000, printRun: 3000 },
  { num: 15, name: 'Venusaur', type: 'grass', rarity: 'holo', kind: 'creature', hp: 100, value: 2400, printRun: 3000 },
  { num: 16, name: 'Zapdos', type: 'lightning', rarity: 'holo', kind: 'creature', hp: 90, value: 800, printRun: 3000 },
  { num: 17, name: 'Beedrill', type: 'grass', rarity: 'rare', kind: 'creature', hp: 80, value: 90, printRun: 5000 },
  { num: 18, name: 'Dragonair', type: 'colorless', rarity: 'rare', kind: 'creature', hp: 80, value: 140, printRun: 5000 },
  { num: 19, name: 'Dugtrio', type: 'fighting', rarity: 'rare', kind: 'creature', hp: 70, value: 70, printRun: 5000 },
  { num: 20, name: 'Electabuzz', type: 'lightning', rarity: 'rare', kind: 'creature', hp: 70, value: 80, printRun: 5000 },
  { num: 21, name: 'Electrode', type: 'lightning', rarity: 'rare', kind: 'creature', hp: 80, value: 60, printRun: 5000 },
  { num: 22, name: 'Pidgeotto', type: 'colorless', rarity: 'rare', kind: 'creature', hp: 60, value: 70, printRun: 5000 },
  { num: 23, name: 'Arcanine', type: 'fire', rarity: 'uncommon', kind: 'creature', hp: 100, value: 45, printRun: 15000 },
  { num: 24, name: 'Charmeleon', type: 'fire', rarity: 'uncommon', kind: 'creature', hp: 80, value: 60, printRun: 15000 },
  { num: 25, name: 'Dewgong', type: 'water', rarity: 'uncommon', kind: 'creature', hp: 80, value: 25, printRun: 15000 },
  { num: 26, name: 'Dratini', type: 'colorless', rarity: 'uncommon', kind: 'creature', hp: 40, value: 35, printRun: 15000 },
  { num: 27, name: 'Farfetch\'d', type: 'colorless', rarity: 'uncommon', kind: 'creature', hp: 50, value: 22, printRun: 15000 },
  { num: 28, name: 'Growlithe', type: 'fire', rarity: 'uncommon', kind: 'creature', hp: 60, value: 30, printRun: 15000 },
  { num: 29, name: 'Haunter', type: 'psychic', rarity: 'uncommon', kind: 'creature', hp: 60, value: 30, printRun: 15000 },
  { num: 30, name: 'Ivysaur', type: 'grass', rarity: 'uncommon', kind: 'creature', hp: 60, value: 40, printRun: 15000 },
  { num: 31, name: 'Jynx', type: 'psychic', rarity: 'uncommon', kind: 'creature', hp: 70, value: 22, printRun: 15000 },
  { num: 32, name: 'Kadabra', type: 'psychic', rarity: 'uncommon', kind: 'creature', hp: 60, value: 35, printRun: 15000 },
  { num: 33, name: 'Kakuna', type: 'grass', rarity: 'uncommon', kind: 'creature', hp: 80, value: 20, printRun: 15000 },
  { num: 34, name: 'Machoke', type: 'fighting', rarity: 'uncommon', kind: 'creature', hp: 80, value: 22, printRun: 15000 },
  { num: 35, name: 'Magikarp', type: 'water', rarity: 'uncommon', kind: 'creature', hp: 30, value: 40, printRun: 15000 },
  { num: 36, name: 'Magmar', type: 'fire', rarity: 'uncommon', kind: 'creature', hp: 50, value: 25, printRun: 15000 },
  { num: 37, name: 'Nidorino', type: 'grass', rarity: 'uncommon', kind: 'creature', hp: 60, value: 22, printRun: 15000 },
  { num: 38, name: 'Poliwhirl', type: 'water', rarity: 'uncommon', kind: 'creature', hp: 60, value: 22, printRun: 15000 },
  { num: 39, name: 'Porygon', type: 'colorless', rarity: 'uncommon', kind: 'creature', hp: 30, value: 28, printRun: 15000 },
  { num: 40, name: 'Raticate', type: 'colorless', rarity: 'uncommon', kind: 'creature', hp: 60, value: 22, printRun: 15000 },
  { num: 41, name: 'Seel', type: 'water', rarity: 'uncommon', kind: 'creature', hp: 60, value: 20, printRun: 15000 },
  { num: 42, name: 'Wartortle', type: 'water', rarity: 'uncommon', kind: 'creature', hp: 70, value: 45, printRun: 15000 },
  { num: 43, name: 'Abra', type: 'psychic', rarity: 'common', kind: 'creature', hp: 30, value: 14, printRun: 22000 },
  { num: 44, name: 'Bulbasaur', type: 'grass', rarity: 'common', kind: 'creature', hp: 40, value: 30, printRun: 22000 },
  { num: 45, name: 'Caterpie', type: 'grass', rarity: 'common', kind: 'creature', hp: 40, value: 12, printRun: 22000 },
  { num: 46, name: 'Charmander', type: 'fire', rarity: 'common', kind: 'creature', hp: 50, value: 32, printRun: 22000 },
  { num: 47, name: 'Diglett', type: 'fighting', rarity: 'common', kind: 'creature', hp: 30, value: 12, printRun: 22000 },
  { num: 48, name: 'Doduo', type: 'colorless', rarity: 'common', kind: 'creature', hp: 50, value: 10, printRun: 22000 },
  { num: 49, name: 'Drowzee', type: 'psychic', rarity: 'common', kind: 'creature', hp: 50, value: 12, printRun: 22000 },
  { num: 50, name: 'Gastly', type: 'psychic', rarity: 'common', kind: 'creature', hp: 30, value: 14, printRun: 22000 },
  { num: 51, name: 'Koffing', type: 'grass', rarity: 'common', kind: 'creature', hp: 50, value: 12, printRun: 22000 },
  { num: 52, name: 'Machop', type: 'fighting', rarity: 'common', kind: 'creature', hp: 50, value: 14, printRun: 22000 },
  { num: 53, name: 'Magnemite', type: 'lightning', rarity: 'common', kind: 'creature', hp: 40, value: 12, printRun: 22000 },
  { num: 54, name: 'Metapod', type: 'grass', rarity: 'common', kind: 'creature', hp: 70, value: 12, printRun: 22000 },
  { num: 55, name: 'Nidoran M', type: 'grass', rarity: 'common', kind: 'creature', hp: 40, value: 12, printRun: 22000 },
  { num: 56, name: 'Onix', type: 'fighting', rarity: 'common', kind: 'creature', hp: 90, value: 14, printRun: 22000 },
  { num: 57, name: 'Pidgey', type: 'colorless', rarity: 'common', kind: 'creature', hp: 40, value: 12, printRun: 22000 },
  { num: 58, name: 'Pikachu', type: 'lightning', rarity: 'common', kind: 'creature', hp: 40, value: 48, printRun: 22000 },
  { num: 59, name: 'Poliwag', type: 'water', rarity: 'common', kind: 'creature', hp: 40, value: 12, printRun: 22000 },
  { num: 60, name: 'Ponyta', type: 'fire', rarity: 'common', kind: 'creature', hp: 40, value: 14, printRun: 22000 },
  { num: 61, name: 'Rattata', type: 'colorless', rarity: 'common', kind: 'creature', hp: 30, value: 12, printRun: 22000 },
  { num: 62, name: 'Sandshrew', type: 'fighting', rarity: 'common', kind: 'creature', hp: 40, value: 12, printRun: 22000 },
  { num: 63, name: 'Squirtle', type: 'water', rarity: 'common', kind: 'creature', hp: 40, value: 30, printRun: 22000 },
  { num: 64, name: 'Starmie', type: 'water', rarity: 'common', kind: 'creature', hp: 60, value: 12, printRun: 22000 },
  { num: 65, name: 'Staryu', type: 'water', rarity: 'common', kind: 'creature', hp: 40, value: 12, printRun: 22000 },
  { num: 66, name: 'Tangela', type: 'grass', rarity: 'common', kind: 'creature', hp: 50, value: 12, printRun: 22000 },
  { num: 67, name: 'Voltorb', type: 'lightning', rarity: 'common', kind: 'creature', hp: 40, value: 12, printRun: 22000 },
  { num: 68, name: 'Vulpix', type: 'fire', rarity: 'common', kind: 'creature', hp: 50, value: 16, printRun: 22000 },
  { num: 69, name: 'Weedle', type: 'grass', rarity: 'common', kind: 'creature', hp: 40, value: 12, printRun: 22000 },
  { num: 70, name: 'Clefairy Doll', type: 'trainer', rarity: 'rare', kind: 'trainer', hp: null, value: 30, printRun: 10000 },
  { num: 71, name: 'Computer Search', type: 'trainer', rarity: 'rare', kind: 'trainer', hp: null, value: 60, printRun: 10000 },
  { num: 72, name: 'Devolution Spray', type: 'trainer', rarity: 'rare', kind: 'trainer', hp: null, value: 25, printRun: 10000 },
  { num: 73, name: 'Impostor Professor Oak', type: 'trainer', rarity: 'rare', kind: 'trainer', hp: null, value: 30, printRun: 10000 },
  { num: 74, name: 'Item Finder', type: 'trainer', rarity: 'rare', kind: 'trainer', hp: null, value: 50, printRun: 10000 },
  { num: 75, name: 'Lass', type: 'trainer', rarity: 'rare', kind: 'trainer', hp: null, value: 45, printRun: 10000 },
  { num: 76, name: 'Pokemon Breeder', type: 'trainer', rarity: 'rare', kind: 'trainer', hp: null, value: 40, printRun: 10000 },
  { num: 77, name: 'Pokemon Trader', type: 'trainer', rarity: 'rare', kind: 'trainer', hp: null, value: 35, printRun: 10000 },
  { num: 78, name: 'Scoop Up', type: 'trainer', rarity: 'rare', kind: 'trainer', hp: null, value: 30, printRun: 10000 },
  { num: 79, name: 'Super Energy Removal', type: 'trainer', rarity: 'rare', kind: 'trainer', hp: null, value: 30, printRun: 10000 },
  { num: 80, name: 'Defender', type: 'trainer', rarity: 'uncommon', kind: 'trainer', hp: null, value: 12, printRun: 30000 },
  { num: 81, name: 'Energy Retrieval', type: 'trainer', rarity: 'uncommon', kind: 'trainer', hp: null, value: 12, printRun: 30000 },
  { num: 82, name: 'Full Heal', type: 'trainer', rarity: 'uncommon', kind: 'trainer', hp: null, value: 10, printRun: 30000 },
  { num: 83, name: 'Maintenance', type: 'trainer', rarity: 'uncommon', kind: 'trainer', hp: null, value: 10, printRun: 30000 },
  { num: 84, name: 'PlusPower', type: 'trainer', rarity: 'uncommon', kind: 'trainer', hp: null, value: 14, printRun: 30000 },
  { num: 85, name: 'Pokemon Center', type: 'trainer', rarity: 'uncommon', kind: 'trainer', hp: null, value: 12, printRun: 30000 },
  { num: 86, name: 'Pokemon Flute', type: 'trainer', rarity: 'uncommon', kind: 'trainer', hp: null, value: 14, printRun: 30000 },
  { num: 87, name: 'Pokedex', type: 'trainer', rarity: 'uncommon', kind: 'trainer', hp: null, value: 12, printRun: 30000 },
  { num: 88, name: 'Professor Oak', type: 'trainer', rarity: 'uncommon', kind: 'trainer', hp: null, value: 25, printRun: 30000 },
  { num: 89, name: 'Revive', type: 'trainer', rarity: 'uncommon', kind: 'trainer', hp: null, value: 12, printRun: 30000 },
  { num: 90, name: 'Super Potion', type: 'trainer', rarity: 'uncommon', kind: 'trainer', hp: null, value: 12, printRun: 30000 },
  { num: 91, name: 'Bill', type: 'trainer', rarity: 'common', kind: 'trainer', hp: null, value: 10, printRun: 44000 },
  { num: 92, name: 'Energy Removal', type: 'trainer', rarity: 'common', kind: 'trainer', hp: null, value: 9, printRun: 44000 },
  { num: 93, name: 'Gust of Wind', type: 'trainer', rarity: 'common', kind: 'trainer', hp: null, value: 10, printRun: 44000 },
  { num: 94, name: 'Potion', type: 'trainer', rarity: 'common', kind: 'trainer', hp: null, value: 8, printRun: 44000 },
  { num: 95, name: 'Switch', type: 'trainer', rarity: 'common', kind: 'trainer', hp: null, value: 9, printRun: 44000 },
  { num: 96, name: 'Double Colorless Energy', type: 'colorless', rarity: 'uncommon', kind: 'energy', hp: null, value: 40, printRun: 60000 },
  { num: 97, name: 'Fighting Energy', type: 'fighting', rarity: 'common', kind: 'energy', hp: null, value: 6, printRun: 60000 },
  { num: 98, name: 'Fire Energy', type: 'fire', rarity: 'common', kind: 'energy', hp: null, value: 8, printRun: 60000 },
  { num: 99, name: 'Grass Energy', type: 'grass', rarity: 'common', kind: 'energy', hp: null, value: 7, printRun: 60000 },
  { num: 100, name: 'Lightning Energy', type: 'lightning', rarity: 'common', kind: 'energy', hp: null, value: 8, printRun: 60000 },
  { num: 101, name: 'Psychic Energy', type: 'psychic', rarity: 'common', kind: 'energy', hp: null, value: 7, printRun: 60000 },
  { num: 102, name: 'Water Energy', type: 'water', rarity: 'common', kind: 'energy', hp: null, value: 7, printRun: 60000 },
    ],
  },
  {
    id: 'tcg-151', name: 'Pokemon 151', year: 2023, size: 165,
    packPrice: 5, boxPrice: 160,
    cards: [
  { num: 1, name: 'Bulbasaur', type: 'grass', rarity: 'common', kind: 'creature', hp: null, value: 0.15, printRun: 220000 },
  { num: 2, name: 'Ivysaur', type: 'grass', rarity: 'rare', kind: 'creature', hp: null, value: 0.8, printRun: 90000 },
  { num: 3, name: 'Venusaur', type: 'grass', rarity: 'holo', kind: 'creature', hp: null, value: 6.0, printRun: 2500 },
  { num: 4, name: 'Charmander', type: 'fire', rarity: 'common', kind: 'creature', hp: null, value: 0.15, printRun: 220000 },
  { num: 5, name: 'Charmeleon', type: 'fire', rarity: 'rare', kind: 'creature', hp: null, value: 0.8, printRun: 90000 },
  { num: 6, name: 'Charizard', type: 'fire', rarity: 'holo', kind: 'creature', hp: null, value: 25.0, printRun: 2500 },
  { num: 7, name: 'Squirtle', type: 'water', rarity: 'common', kind: 'creature', hp: null, value: 0.15, printRun: 220000 },
  { num: 8, name: 'Wartortle', type: 'water', rarity: 'rare', kind: 'creature', hp: null, value: 0.8, printRun: 90000 },
  { num: 9, name: 'Blastoise', type: 'water', rarity: 'holo', kind: 'creature', hp: null, value: 8.0, printRun: 2500 },
  { num: 10, name: 'Caterpie', type: 'grass', rarity: 'common', kind: 'creature', hp: null, value: 0.15, printRun: 220000 },
  { num: 11, name: 'Metapod', type: 'grass', rarity: 'common', kind: 'creature', hp: null, value: 0.15, printRun: 220000 },
  { num: 12, name: 'Butterfree', type: 'grass', rarity: 'holo', kind: 'creature', hp: null, value: 2.5, printRun: 40000 },
  { num: 13, name: 'Weedle', type: 'grass', rarity: 'common', kind: 'creature', hp: null, value: 0.15, printRun: 220000 },
  { num: 14, name: 'Kakuna', type: 'grass', rarity: 'common', kind: 'creature', hp: null, value: 0.15, printRun: 220000 },
  { num: 15, name: 'Beedrill', type: 'grass', rarity: 'uncommon', kind: 'creature', hp: null, value: 0.3, printRun: 160000 },
  { num: 16, name: 'Pidgey', type: 'colorless', rarity: 'common', kind: 'creature', hp: null, value: 0.15, printRun: 220000 },
  { num: 17, name: 'Pidgeotto', type: 'colorless', rarity: 'rare', kind: 'creature', hp: null, value: 0.8, printRun: 90000 },
  { num: 18, name: 'Pidgeot', type: 'colorless', rarity: 'holo', kind: 'creature', hp: null, value: 2.5, printRun: 40000 },
  { num: 19, name: 'Rattata', type: 'colorless', rarity: 'common', kind: 'creature', hp: null, value: 0.15, printRun: 220000 },
  { num: 20, name: 'Raticate', type: 'colorless', rarity: 'common', kind: 'creature', hp: null, value: 0.15, printRun: 220000 },
  { num: 21, name: 'Spearow', type: 'colorless', rarity: 'uncommon', kind: 'creature', hp: null, value: 0.3, printRun: 160000 },
  { num: 22, name: 'Fearow', type: 'colorless', rarity: 'common', kind: 'creature', hp: null, value: 0.15, printRun: 220000 },
  { num: 23, name: 'Ekans', type: 'grass', rarity: 'common', kind: 'creature', hp: null, value: 0.15, printRun: 220000 },
  { num: 24, name: 'Arbok', type: 'grass', rarity: 'uncommon', kind: 'creature', hp: null, value: 0.3, printRun: 160000 },
  { num: 25, name: 'Pikachu', type: 'lightning', rarity: 'common', kind: 'creature', hp: null, value: 0.15, printRun: 220000 },
  { num: 26, name: 'Raichu', type: 'lightning', rarity: 'holo', kind: 'creature', hp: null, value: 2.5, printRun: 40000 },
  { num: 27, name: 'Sandshrew', type: 'fighting', rarity: 'uncommon', kind: 'creature', hp: null, value: 0.3, printRun: 160000 },
  { num: 28, name: 'Sandslash', type: 'fighting', rarity: 'rare', kind: 'creature', hp: null, value: 0.8, printRun: 90000 },
  { num: 29, name: 'Nidoran F', type: 'grass', rarity: 'common', kind: 'creature', hp: null, value: 0.15, printRun: 220000 },
  { num: 30, name: 'Nidorina', type: 'grass', rarity: 'rare', kind: 'creature', hp: null, value: 0.8, printRun: 90000 },
  { num: 31, name: 'Nidoqueen', type: 'grass', rarity: 'holo', kind: 'creature', hp: null, value: 2.5, printRun: 40000 },
  { num: 32, name: 'Nidoran M', type: 'grass', rarity: 'common', kind: 'creature', hp: null, value: 0.15, printRun: 220000 },
  { num: 33, name: 'Nidorino', type: 'grass', rarity: 'rare', kind: 'creature', hp: null, value: 0.8, printRun: 90000 },
  { num: 34, name: 'Nidoking', type: 'grass', rarity: 'holo', kind: 'creature', hp: null, value: 2.5, printRun: 40000 },
  { num: 35, name: 'Clefairy', type: 'colorless', rarity: 'common', kind: 'creature', hp: null, value: 0.15, printRun: 220000 },
  { num: 36, name: 'Clefable', type: 'colorless', rarity: 'holo', kind: 'creature', hp: null, value: 2.5, printRun: 40000 },
  { num: 37, name: 'Vulpix', type: 'fire', rarity: 'common', kind: 'creature', hp: null, value: 0.15, printRun: 220000 },
  { num: 38, name: 'Ninetales', type: 'fire', rarity: 'holo', kind: 'creature', hp: null, value: 2.5, printRun: 40000 },
  { num: 39, name: 'Jigglypuff', type: 'colorless', rarity: 'uncommon', kind: 'creature', hp: null, value: 0.3, printRun: 160000 },
  { num: 40, name: 'Wigglytuff', type: 'colorless', rarity: 'common', kind: 'creature', hp: null, value: 0.15, printRun: 220000 },
  { num: 41, name: 'Zubat', type: 'grass', rarity: 'common', kind: 'creature', hp: null, value: 0.15, printRun: 220000 },
  { num: 42, name: 'Golbat', type: 'grass', rarity: 'uncommon', kind: 'creature', hp: null, value: 0.3, printRun: 160000 },
  { num: 43, name: 'Oddish', type: 'grass', rarity: 'common', kind: 'creature', hp: null, value: 0.15, printRun: 220000 },
  { num: 44, name: 'Gloom', type: 'grass', rarity: 'rare', kind: 'creature', hp: null, value: 0.8, printRun: 90000 },
  { num: 45, name: 'Vileplume', type: 'grass', rarity: 'holo', kind: 'creature', hp: null, value: 2.5, printRun: 40000 },
  { num: 46, name: 'Paras', type: 'grass', rarity: 'common', kind: 'creature', hp: null, value: 0.15, printRun: 220000 },
  { num: 47, name: 'Parasect', type: 'grass', rarity: 'common', kind: 'creature', hp: null, value: 0.15, printRun: 220000 },
  { num: 48, name: 'Venonat', type: 'grass', rarity: 'uncommon', kind: 'creature', hp: null, value: 0.3, printRun: 160000 },
  { num: 49, name: 'Venomoth', type: 'grass', rarity: 'common', kind: 'creature', hp: null, value: 0.15, printRun: 220000 },
  { num: 50, name: 'Diglett', type: 'fighting', rarity: 'common', kind: 'creature', hp: null, value: 0.15, printRun: 220000 },
  { num: 51, name: 'Dugtrio', type: 'fighting', rarity: 'uncommon', kind: 'creature', hp: null, value: 0.3, printRun: 160000 },
  { num: 52, name: 'Meowth', type: 'colorless', rarity: 'common', kind: 'creature', hp: null, value: 0.15, printRun: 220000 },
  { num: 53, name: 'Persian', type: 'colorless', rarity: 'common', kind: 'creature', hp: null, value: 0.15, printRun: 220000 },
  { num: 54, name: 'Psyduck', type: 'water', rarity: 'uncommon', kind: 'creature', hp: null, value: 0.3, printRun: 160000 },
  { num: 55, name: 'Golduck', type: 'water', rarity: 'rare', kind: 'creature', hp: null, value: 0.8, printRun: 90000 },
  { num: 56, name: 'Mankey', type: 'fighting', rarity: 'common', kind: 'creature', hp: null, value: 0.15, printRun: 220000 },
  { num: 57, name: 'Primeape', type: 'fighting', rarity: 'rare', kind: 'creature', hp: null, value: 0.8, printRun: 90000 },
  { num: 58, name: 'Growlithe', type: 'fire', rarity: 'common', kind: 'creature', hp: null, value: 0.15, printRun: 220000 },
  { num: 59, name: 'Arcanine', type: 'fire', rarity: 'holo', kind: 'creature', hp: null, value: 2.5, printRun: 40000 },
  { num: 60, name: 'Poliwag', type: 'water', rarity: 'uncommon', kind: 'creature', hp: null, value: 0.3, printRun: 160000 },
  { num: 61, name: 'Poliwhirl', type: 'water', rarity: 'rare', kind: 'creature', hp: null, value: 0.8, printRun: 90000 },
  { num: 62, name: 'Poliwrath', type: 'water', rarity: 'holo', kind: 'creature', hp: null, value: 2.5, printRun: 40000 },
  { num: 63, name: 'Abra', type: 'psychic', rarity: 'uncommon', kind: 'creature', hp: null, value: 0.3, printRun: 160000 },
  { num: 64, name: 'Kadabra', type: 'psychic', rarity: 'rare', kind: 'creature', hp: null, value: 0.8, printRun: 90000 },
  { num: 65, name: 'Alakazam', type: 'psychic', rarity: 'holo', kind: 'creature', hp: null, value: 3.5, printRun: 2500 },
  { num: 66, name: 'Machop', type: 'fighting', rarity: 'uncommon', kind: 'creature', hp: null, value: 0.3, printRun: 160000 },
  { num: 67, name: 'Machoke', type: 'fighting', rarity: 'rare', kind: 'creature', hp: null, value: 0.8, printRun: 90000 },
  { num: 68, name: 'Machamp', type: 'fighting', rarity: 'holo', kind: 'creature', hp: null, value: 2.5, printRun: 40000 },
  { num: 69, name: 'Bellsprout', type: 'grass', rarity: 'uncommon', kind: 'creature', hp: null, value: 0.3, printRun: 160000 },
  { num: 70, name: 'Weepinbell', type: 'grass', rarity: 'rare', kind: 'creature', hp: null, value: 0.8, printRun: 90000 },
  { num: 71, name: 'Victreebel', type: 'grass', rarity: 'holo', kind: 'creature', hp: null, value: 2.5, printRun: 40000 },
  { num: 72, name: 'Tentacool', type: 'water', rarity: 'uncommon', kind: 'creature', hp: null, value: 0.3, printRun: 160000 },
  { num: 73, name: 'Tentacruel', type: 'water', rarity: 'common', kind: 'creature', hp: null, value: 0.15, printRun: 220000 },
  { num: 74, name: 'Geodude', type: 'fighting', rarity: 'common', kind: 'creature', hp: null, value: 0.15, printRun: 220000 },
  { num: 75, name: 'Graveler', type: 'fighting', rarity: 'rare', kind: 'creature', hp: null, value: 0.8, printRun: 90000 },
  { num: 76, name: 'Golem', type: 'fighting', rarity: 'holo', kind: 'creature', hp: null, value: 2.5, printRun: 40000 },
  { num: 77, name: 'Ponyta', type: 'fire', rarity: 'common', kind: 'creature', hp: null, value: 0.15, printRun: 220000 },
  { num: 78, name: 'Rapidash', type: 'fire', rarity: 'holo', kind: 'creature', hp: null, value: 2.5, printRun: 40000 },
  { num: 79, name: 'Slowpoke', type: 'psychic', rarity: 'common', kind: 'creature', hp: null, value: 0.15, printRun: 220000 },
  { num: 80, name: 'Slowbro', type: 'psychic', rarity: 'rare', kind: 'creature', hp: null, value: 0.8, printRun: 90000 },
  { num: 81, name: 'Magnemite', type: 'lightning', rarity: 'uncommon', kind: 'creature', hp: null, value: 0.3, printRun: 160000 },
  { num: 82, name: 'Magneton', type: 'lightning', rarity: 'rare', kind: 'creature', hp: null, value: 0.8, printRun: 90000 },
  { num: 83, name: 'Farfetch\'d', type: 'colorless', rarity: 'common', kind: 'creature', hp: null, value: 0.15, printRun: 220000 },
  { num: 84, name: 'Doduo', type: 'colorless', rarity: 'uncommon', kind: 'creature', hp: null, value: 0.3, printRun: 160000 },
  { num: 85, name: 'Dodrio', type: 'colorless', rarity: 'common', kind: 'creature', hp: null, value: 0.15, printRun: 220000 },
  { num: 86, name: 'Seel', type: 'water', rarity: 'common', kind: 'creature', hp: null, value: 0.15, printRun: 220000 },
  { num: 87, name: 'Dewgong', type: 'water', rarity: 'rare', kind: 'creature', hp: null, value: 0.8, printRun: 90000 },
  { num: 88, name: 'Grimer', type: 'grass', rarity: 'common', kind: 'creature', hp: null, value: 0.15, printRun: 220000 },
  { num: 89, name: 'Muk', type: 'grass', rarity: 'holo', kind: 'creature', hp: null, value: 2.5, printRun: 40000 },
  { num: 90, name: 'Shellder', type: 'water', rarity: 'uncommon', kind: 'creature', hp: null, value: 0.3, printRun: 160000 },
  { num: 91, name: 'Cloyster', type: 'water', rarity: 'rare', kind: 'creature', hp: null, value: 0.8, printRun: 90000 },
  { num: 92, name: 'Gastly', type: 'psychic', rarity: 'common', kind: 'creature', hp: null, value: 0.15, printRun: 220000 },
  { num: 93, name: 'Haunter', type: 'psychic', rarity: 'rare', kind: 'creature', hp: null, value: 0.8, printRun: 90000 },
  { num: 94, name: 'Gengar', type: 'psychic', rarity: 'holo', kind: 'creature', hp: null, value: 4.0, printRun: 2500 },
  { num: 95, name: 'Onix', type: 'fighting', rarity: 'common', kind: 'creature', hp: null, value: 0.15, printRun: 220000 },
  { num: 96, name: 'Drowzee', type: 'psychic', rarity: 'uncommon', kind: 'creature', hp: null, value: 0.3, printRun: 160000 },
  { num: 97, name: 'Hypno', type: 'psychic', rarity: 'rare', kind: 'creature', hp: null, value: 0.8, printRun: 90000 },
  { num: 98, name: 'Krabby', type: 'water', rarity: 'common', kind: 'creature', hp: null, value: 0.15, printRun: 220000 },
  { num: 99, name: 'Kingler', type: 'water', rarity: 'rare', kind: 'creature', hp: null, value: 0.8, printRun: 90000 },
  { num: 100, name: 'Voltorb', type: 'lightning', rarity: 'common', kind: 'creature', hp: null, value: 0.15, printRun: 220000 },
  { num: 101, name: 'Electrode', type: 'lightning', rarity: 'rare', kind: 'creature', hp: null, value: 0.8, printRun: 90000 },
  { num: 102, name: 'Exeggcute', type: 'grass', rarity: 'uncommon', kind: 'creature', hp: null, value: 0.3, printRun: 160000 },
  { num: 103, name: 'Exeggutor', type: 'grass', rarity: 'holo', kind: 'creature', hp: null, value: 2.5, printRun: 40000 },
  { num: 104, name: 'Cubone', type: 'fighting', rarity: 'common', kind: 'creature', hp: null, value: 0.15, printRun: 220000 },
  { num: 105, name: 'Marowak', type: 'fighting', rarity: 'rare', kind: 'creature', hp: null, value: 0.8, printRun: 90000 },
  { num: 106, name: 'Hitmonlee', type: 'fighting', rarity: 'rare', kind: 'creature', hp: null, value: 0.8, printRun: 90000 },
  { num: 107, name: 'Hitmonchan', type: 'fighting', rarity: 'rare', kind: 'creature', hp: null, value: 0.8, printRun: 90000 },
  { num: 108, name: 'Lickitung', type: 'colorless', rarity: 'uncommon', kind: 'creature', hp: null, value: 0.3, printRun: 160000 },
  { num: 109, name: 'Koffing', type: 'grass', rarity: 'common', kind: 'creature', hp: null, value: 0.15, printRun: 220000 },
  { num: 110, name: 'Weezing', type: 'grass', rarity: 'rare', kind: 'creature', hp: null, value: 0.8, printRun: 90000 },
  { num: 111, name: 'Rhyhorn', type: 'fighting', rarity: 'uncommon', kind: 'creature', hp: null, value: 0.3, printRun: 160000 },
  { num: 112, name: 'Rhydon', type: 'fighting', rarity: 'holo', kind: 'creature', hp: null, value: 2.5, printRun: 40000 },
  { num: 113, name: 'Chansey', type: 'colorless', rarity: 'rare', kind: 'creature', hp: null, value: 0.8, printRun: 90000 },
  { num: 114, name: 'Tangela', type: 'grass', rarity: 'uncommon', kind: 'creature', hp: null, value: 0.3, printRun: 160000 },
  { num: 115, name: 'Kangaskhan', type: 'colorless', rarity: 'holo', kind: 'creature', hp: null, value: 2.5, printRun: 40000 },
  { num: 116, name: 'Horsea', type: 'water', rarity: 'common', kind: 'creature', hp: null, value: 0.15, printRun: 220000 },
  { num: 117, name: 'Seadra', type: 'water', rarity: 'rare', kind: 'creature', hp: null, value: 0.8, printRun: 90000 },
  { num: 118, name: 'Goldeen', type: 'water', rarity: 'common', kind: 'creature', hp: null, value: 0.15, printRun: 220000 },
  { num: 119, name: 'Seaking', type: 'water', rarity: 'rare', kind: 'creature', hp: null, value: 0.8, printRun: 90000 },
  { num: 120, name: 'Staryu', type: 'water', rarity: 'uncommon', kind: 'creature', hp: null, value: 0.3, printRun: 160000 },
  { num: 121, name: 'Starmie', type: 'water', rarity: 'holo', kind: 'creature', hp: null, value: 2.5, printRun: 40000 },
  { num: 122, name: 'Mr. Mime', type: 'psychic', rarity: 'rare', kind: 'creature', hp: null, value: 0.8, printRun: 90000 },
  { num: 123, name: 'Scyther', type: 'grass', rarity: 'holo', kind: 'creature', hp: null, value: 2.5, printRun: 40000 },
  { num: 124, name: 'Jynx', type: 'psychic', rarity: 'holo', kind: 'creature', hp: null, value: 2.5, printRun: 40000 },
  { num: 125, name: 'Electabuzz', type: 'lightning', rarity: 'holo', kind: 'creature', hp: null, value: 2.5, printRun: 40000 },
  { num: 126, name: 'Magmar', type: 'fire', rarity: 'holo', kind: 'creature', hp: null, value: 2.5, printRun: 40000 },
  { num: 127, name: 'Pinsir', type: 'grass', rarity: 'holo', kind: 'creature', hp: null, value: 2.5, printRun: 40000 },
  { num: 128, name: 'Tauros', type: 'colorless', rarity: 'rare', kind: 'creature', hp: null, value: 0.8, printRun: 90000 },
  { num: 129, name: 'Magikarp', type: 'water', rarity: 'uncommon', kind: 'creature', hp: null, value: 0.3, printRun: 160000 },
  { num: 130, name: 'Gyarados', type: 'water', rarity: 'holo', kind: 'creature', hp: null, value: 2.5, printRun: 40000 },
  { num: 131, name: 'Lapras', type: 'water', rarity: 'holo', kind: 'creature', hp: null, value: 2.5, printRun: 40000 },
  { num: 132, name: 'Ditto', type: 'colorless', rarity: 'uncommon', kind: 'creature', hp: null, value: 0.3, printRun: 160000 },
  { num: 133, name: 'Eevee', type: 'colorless', rarity: 'rare', kind: 'creature', hp: null, value: 0.8, printRun: 90000 },
  { num: 134, name: 'Vaporeon', type: 'water', rarity: 'holo', kind: 'creature', hp: null, value: 2.5, printRun: 40000 },
  { num: 135, name: 'Jolteon', type: 'lightning', rarity: 'holo', kind: 'creature', hp: null, value: 2.5, printRun: 40000 },
  { num: 136, name: 'Flareon', type: 'fire', rarity: 'holo', kind: 'creature', hp: null, value: 2.5, printRun: 40000 },
  { num: 137, name: 'Porygon', type: 'colorless', rarity: 'rare', kind: 'creature', hp: null, value: 0.8, printRun: 90000 },
  { num: 138, name: 'Omanyte', type: 'water', rarity: 'uncommon', kind: 'creature', hp: null, value: 0.3, printRun: 160000 },
  { num: 139, name: 'Omastar', type: 'water', rarity: 'rare', kind: 'creature', hp: null, value: 0.8, printRun: 90000 },
  { num: 140, name: 'Kabuto', type: 'fighting', rarity: 'common', kind: 'creature', hp: null, value: 0.15, printRun: 220000 },
  { num: 141, name: 'Kabutops', type: 'fighting', rarity: 'rare', kind: 'creature', hp: null, value: 0.8, printRun: 90000 },
  { num: 142, name: 'Aerodactyl', type: 'fighting', rarity: 'holo', kind: 'creature', hp: null, value: 2.5, printRun: 40000 },
  { num: 143, name: 'Snorlax', type: 'colorless', rarity: 'holo', kind: 'creature', hp: null, value: 2.5, printRun: 40000 },
  { num: 144, name: 'Articuno', type: 'water', rarity: 'holo', kind: 'creature', hp: null, value: 2.5, printRun: 40000 },
  { num: 145, name: 'Zapdos', type: 'lightning', rarity: 'holo', kind: 'creature', hp: null, value: 4.0, printRun: 2500 },
  { num: 146, name: 'Moltres', type: 'fire', rarity: 'holo', kind: 'creature', hp: null, value: 2.5, printRun: 40000 },
  { num: 147, name: 'Dratini', type: 'colorless', rarity: 'rare', kind: 'creature', hp: null, value: 0.8, printRun: 90000 },
  { num: 148, name: 'Dragonair', type: 'colorless', rarity: 'rare', kind: 'creature', hp: null, value: 0.8, printRun: 90000 },
  { num: 149, name: 'Dragonite', type: 'colorless', rarity: 'holo', kind: 'creature', hp: null, value: 2.5, printRun: 40000 },
  { num: 150, name: 'Mewtwo', type: 'psychic', rarity: 'holo', kind: 'creature', hp: null, value: 2.5, printRun: 40000 },
  { num: 151, name: 'Mew', type: 'psychic', rarity: 'holo', kind: 'creature', hp: null, value: 8.0, printRun: 2500 },
  { num: 199, name: 'Charizard ex', type: 'fire', rarity: 'chase', kind: 'creature', hp: null, value: 240.0, printRun: 900, outOf: 165 },
    ],
  },
];
